only use C++ 11 compiler if std::unordered_map is available
For some combinations of clang and the libstdc++, enabling
C++ 11 results in the error

    error: use of undeclared identifier '__float128'

This results in the failure to use std::unordered_map (which is ok,
since there is an alternative implementation), but it may also result
in a failure to use NTL.
Revert to the original C++ compiler when std::unordered_map cannot
be used such that such failures would not affect the detection of NTL.

Signed-off-by: Sven Verdoolaege <skimo@kotnet.org>